-- Phase 1 exercise catalog seed (one-time, AI-assisted research pass, not a
-- runtime pipeline -- see
-- docs/superpowers/specs/2026-06-24-exercise-seed-design.md). Two parts:
-- (1) backfill the 17 v1 rows' new v2 columns (added inert/nullable by
-- 20260623142500_expand_exercises.sql, never populated until now) so they
-- are not left under-tagged relative to the rest of the catalog;
-- (2) insert 172 new researched rows covering every realistic
-- movement_pattern x exercise_type combination, equipment variants as
-- separate rows, real demo video URLs sourced via web search wherever
-- findable, and 5+ is_corrective rows for each of the 5 pain-relevant body
-- parts (neck, ankles, hips, hamstrings, shoulders) per CLAUDE.md's
-- non-negotiables. Total catalog size after this migration: 189 rows
-- (17 backfilled + 172 new), within the spec's 100-200 target range counted
-- against the new rows alone and comfortably within range counted against
-- the whole table.
--
-- This file's INSERT statement was generated by
-- supabase/seed/generate_exercise_migration.py from the reviewed draft at
-- supabase/seed/exercise-catalog-v2-draft.csv -- regenerate by running that
-- script if the CSV ever changes; do not hand-edit the VALUES list without
-- also updating the CSV, or the two will drift.

-- ---------------------------------------------------------------------
-- Part 1: backfill the 17 v1 rows' v2 columns.
-- Matched by exact existing `name` (no id literals needed -- name is
-- unique across the v1 seed and this migration's new rows use distinct
-- names from all 17, confirmed by the validation script's duplicate-name
-- style check). Only the 9 v2 columns are touched; name, movement_pattern,
-- demo_video_url, is_complex are left exactly as
-- 20260622000812_seed_exercises.sql set them.
-- ---------------------------------------------------------------------

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['neck'],
  evidence_rationale = 'Per CLAUDE.md: corrects forward-head posture, a common contributor to chronic neck stiffness via deep cervical flexor activation -- the first Thursday-mobility-block corrective entry for neck.',
  equipment_needed = array['bodyweight'],
  default_sets = 3,
  default_rep_range = '10 reps',
  unilateral = false,
  is_corrective = true
where name = 'Chin tucks';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['thoracic_spine'],
  evidence_rationale = 'Thursday mobility block: per CLAUDE.md, neck pain''s root cause is treated as thoracic spine, not the neck itself -- this directly extends the thoracic segments that compensate for poor neck mobility.',
  equipment_needed = array['foam_roller'],
  default_sets = 2,
  default_rep_range = '8-10 reps',
  unilateral = false,
  is_corrective = true
where name = 'Thoracic extension on foam roller';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['neck'],
  evidence_rationale = 'Thursday mobility block: targets the levator scapulae specifically, a primary muscle implicated in chronic upper-trap/neck stiffness.',
  equipment_needed = array['bodyweight'],
  default_sets = 1,
  default_rep_range = '30-45s hold/side',
  unilateral = true,
  is_corrective = true
where name = 'Levator scapulae stretch';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['ankles'],
  evidence_rationale = 'Per CLAUDE.md: single highest-leverage ankle-mobility intervention -- joint-distraction mobilization improves dorsiflexion range directly at the joint line.',
  equipment_needed = array['resistance_band'],
  default_sets = 3,
  default_rep_range = '10 reps + 30-60s hold',
  unilateral = true,
  is_corrective = true
where name = 'Banded ankle distraction';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['ankles'],
  evidence_rationale = 'Weekly-tracked ankle dorsiflexion measure; per CLAUDE.md, used to monitor ankle mobility progress over time, not just train it.',
  equipment_needed = array['wall'],
  default_sets = 1,
  default_rep_range = 'measure both sides',
  unilateral = true,
  is_corrective = true
where name = 'Wall ankle test (knee-to-wall)';

update exercises set
  exercise_type = 'balance',
  target_goals = array['total_body_resilience'],
  body_parts = array['ankles'],
  evidence_rationale = 'Proprioceptive ankle/balance work; tracks single-leg stability improvement directly relevant to lateral-movement injury risk.',
  equipment_needed = array['bodyweight'],
  default_sets = 3,
  default_rep_range = '30-45s hold',
  unilateral = true,
  is_corrective = true
where name = 'Single-leg balance, eyes closed';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility'],
  body_parts = array['hips'],
  evidence_rationale = 'Thursday mobility block: internal/external hip rotation stretch in the 90/90 position, ~3 min/side per CLAUDE.md.',
  equipment_needed = array['bodyweight'],
  default_sets = 1,
  default_rep_range = '3 min/side',
  unilateral = true,
  is_corrective = true
where name = '90/90 hip stretch';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['hamstrings'],
  evidence_rationale = 'Thursday mobility block: contract-relax PNF stretching produces larger acute range-of-motion gains than static stretching alone.',
  equipment_needed = array['bodyweight', 'strap'],
  default_sets = 1,
  default_rep_range = '3 cycles/side',
  unilateral = true,
  is_corrective = true
where name = 'PNF hamstring stretch';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility'],
  body_parts = array['hips'],
  evidence_rationale = 'Thursday mobility block: deep hip-flexor/quad stretch; directly targets the anterior hip tightness that limits squat depth.',
  equipment_needed = array['wall_or_couch'],
  default_sets = 1,
  default_rep_range = '90-120s hold/side',
  unilateral = true,
  is_corrective = true
where name = 'Couch stretch';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['hips', 'hamstrings', 'ankles'],
  evidence_rationale = 'Thursday mobility block: long-duration end-range squat hold restores hip/ankle/hamstring mobility together, distinct in depth from a pre-lift warmup.',
  equipment_needed = array['bodyweight'],
  default_sets = 1,
  default_rep_range = '5 min hold',
  unilateral = false,
  is_corrective = true
where name = 'Deep squat hold';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['shoulders', 'hamstrings', 'ankles'],
  evidence_rationale = 'Thursday mobility block: yoga down-dog progression simultaneously loads shoulder flexion, hamstring length, and ankle dorsiflexion.',
  equipment_needed = array['yoga_mat'],
  default_sets = 1,
  default_rep_range = '45-60s hold',
  unilateral = false,
  is_corrective = true
where name = 'Down dog progression';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['shoulders'],
  evidence_rationale = 'Thursday mobility block: targets posterior shoulder-capsule tightness specifically on the right -- addresses CLAUDE.md''s right-side-dominance pattern.',
  equipment_needed = array['bodyweight'],
  default_sets = 1,
  default_rep_range = '30-45s hold',
  unilateral = true,
  is_corrective = true
where name = 'Sleeper stretch (right)';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['shoulders'],
  evidence_rationale = 'Thursday mobility block: controlled articular rotations through the shoulder''s full range build active mobility and joint-capsule health.',
  equipment_needed = array['bodyweight'],
  default_sets = 2,
  default_rep_range = '5 reps/side',
  unilateral = true,
  is_corrective = true
where name = 'Shoulder CARs';

update exercises set
  exercise_type = 'strength',
  target_goals = array['total_body_resilience'],
  body_parts = array['hamstrings'],
  evidence_rationale = 'Per CLAUDE.md: strongest evidence base of any single exercise for hamstring-strain injury prevention; programmed every lower day.',
  equipment_needed = array['bodyweight', 'partner_or_bench'],
  default_sets = 3,
  default_rep_range = '5-8',
  unilateral = false,
  is_corrective = true
where name = 'Nordic hamstring curl';

update exercises set
  exercise_type = 'strength',
  target_goals = array['total_body_resilience', 'mobility_flexibility'],
  body_parts = array['ankles', 'knees', 'hips'],
  evidence_rationale = 'Per CLAUDE.md: every lower day, ankle resilience -- deep knee-over-toe range builds ankle dorsiflexion tolerance and knee resilience.',
  equipment_needed = array['dumbbell'],
  default_sets = 3,
  default_rep_range = '8-12',
  unilateral = true,
  is_corrective = false
where name = 'ATG split squat';

update exercises set
  exercise_type = 'strength',
  target_goals = array['total_body_resilience'],
  body_parts = array['hips', 'hamstrings'],
  evidence_rationale = 'Per CLAUDE.md: targets adductor/groin strength, a common gap in lateral-sport injury prevention (pickleball''s side-to-side demand).',
  equipment_needed = array['bench'],
  default_sets = 3,
  default_rep_range = '20-30s hold/side',
  unilateral = true,
  is_corrective = true
where name = 'Copenhagen plank';

update exercises set
  exercise_type = 'mobility_stretch',
  target_goals = array['mobility_flexibility', 'total_body_resilience'],
  body_parts = array['lower_back', 'hamstrings'],
  evidence_rationale = 'Per CLAUDE.md: targets spine and hamstring flexibility through controlled segmental spinal flexion under light load.',
  equipment_needed = array['light_barbell_or_dumbbell'],
  default_sets = 2,
  default_rep_range = '8-10',
  unilateral = false,
  is_corrective = true
where name = 'Jefferson curl';

-- ---------------------------------------------------------------------
-- Part 2: insert 172 new researched rows.
-- ---------------------------------------------------------------------

insert into exercises (
  name, movement_pattern, exercise_type, target_goals, body_parts,
  evidence_rationale, equipment_needed, default_sets, default_rep_range,
  unilateral, is_corrective, demo_video_url, is_complex
) values
  ('Barbell Back Squat', 'squat', 'strength', array['strength_power', 'aesthetic_physique'], array['hips', 'knees', 'lower_back'], 'Foundational bilateral compound for lower-body strength and hypertrophy; high evidence base for quad/glute development.', array['barbell', 'squat_rack'], 4, '5-8', false, false, 'https://www.youtube.com/watch?v=ultWZbUMPL8', true),
  ('Front Squat', 'squat', 'strength', array['strength_power', 'aesthetic_physique'], array['hips', 'knees'], 'More quad-dominant and torso-upright than the back squat; reduces lower-back shear load while still building bilateral leg strength.', array['barbell', 'squat_rack'], 3, '5-8', false, false, 'https://www.youtube.com/watch?v=tttgZRReVDU', true),
  ('Goblet Squat', 'squat', 'strength', array['aesthetic_physique', 'total_body_resilience'], array['hips', 'knees'], 'Easier bar-path and depth cueing than a barbell squat; good entry point for squat-pattern volume without heavy axial load.', array['dumbbell'], 3, '10-15', false, false, 'https://www.youtube.com/watch?v=MeIiIdhvXT4', false),
  ('Smith Machine Squat', 'squat', 'strength', array['aesthetic_physique', 'strength_power'], array['hips', 'knees'], 'Fixed bar path lets lifters push closer to failure safely; useful for hypertrophy accumulation without a spotter.', array['smith_machine'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=N9LOY2x_4Wc', false),
  ('Bulgarian Split Squat', 'squat', 'strength', array['strength_power', 'total_body_resilience'], array['hips', 'knees', 'ankles'], 'Single-leg squat pattern that corrects left/right strength asymmetry and trains hip stability through a long range of motion.', array['dumbbell', 'bench'], 3, '8-12', true, false, 'https://www.youtube.com/watch?v=2C-uNgKwPLE', true),
  ('Cossack Squat', 'squat', 'strength', array['total_body_resilience', 'mobility_flexibility'], array['ankles', 'knees', 'hips'], 'Lateral squat variant building ankle and hip mobility under load through a wide deep stance; complements ATG split squat''s sagittal-plane ankle work with a frontal-plane challenge.', array['bodyweight'], 3, '6-8/side', true, false, 'https://www.youtube.com/watch?v=2C-uNgKwPLE', true),
  ('Leg Press', 'squat', 'strength', array['aesthetic_physique', 'strength_power'], array['hips', 'knees'], 'Machine-stabilized bilateral squat pattern; lets lifters load volume safely without balance/bracing demands.', array['leg_press_machine'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=IZxyjW7MPJQ', false),
  ('Hack Squat', 'squat', 'strength', array['aesthetic_physique', 'strength_power'], array['hips', 'knees'], 'Fixed-path machine squat emphasizing quads with reduced lower-back shear versus a free barbell squat.', array['hack_squat_machine'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=jK6w6PZNmHg', false),
  ('Pistol Squat', 'squat', 'strength', array['total_body_resilience', 'strength_power'], array['hips', 'knees', 'ankles'], 'Advanced unilateral bodyweight squat building single-leg strength, ankle dorsiflexion, and balance simultaneously.', array['bodyweight'], 3, '3-6', true, false, 'https://www.youtube.com/watch?v=vq5-N1JJlfA', true),
  ('Box Squat', 'squat', 'strength', array['strength_power'], array['hips', 'lower_back'], 'Teaches hip-hinge depth control and posterior-chain engagement out of the bottom of a squat; common powerlifting accessory.', array['barbell', 'squat_rack', 'box'], 3, '5-8', false, false, 'https://www.youtube.com/watch?v=ARkXr5yRZUM', true),
  ('Walking Lunge', 'squat', 'strength', array['aesthetic_physique', 'total_body_resilience'], array['hips', 'knees'], 'Dynamic unilateral lower-body pattern that builds single-leg strength and balance through a long stride.', array['dumbbell'], 3, '10-12', true, false, 'https://www.youtube.com/watch?v=L8fvypPrzzs', false),
  ('Step-Up', 'squat', 'strength', array['total_body_resilience', 'strength_power'], array['hips', 'knees'], 'Unilateral squat-pattern movement that closely mirrors stair/uneven-terrain demand; strong carryover to daily function.', array['dumbbell', 'box'], 3, '8-12', true, false, 'https://www.youtube.com/watch?v=7eP9C4iWFTM', false),
  ('Wall Sit', 'squat', 'strength', array['total_body_resilience'], array['hips', 'knees'], 'Isometric squat hold; low-impact way to build quad endurance without joint loading, useful on lower-readiness days.', array['bodyweight'], 3, '30-60s hold', false, false, 'https://www.youtube.com/watch?v=y-wV4Venusw', false),
  ('Box Jump', 'squat', 'plyometric', array['strength_power', 'total_body_resilience'], array['hips', 'knees', 'ankles'], 'Explosive triple-extension power development; CLAUDE.md flags plyometrics as part of the program''s high-leverage toolkit.', array['plyo_box'], 3, '3-5 reps', false, false, 'https://www.youtube.com/watch?v=52ZzJgCnmxA', true),
  ('Jump Squat', 'squat', 'plyometric', array['strength_power'], array['hips', 'knees'], 'Loads the squat pattern with explosive intent; builds rate of force development on top of squat strength.', array['bodyweight'], 3, '6-8 reps', false, false, 'https://www.youtube.com/watch?v=A1uZcoy3M_Q', false),
  ('Asian Squat Hold', 'squat', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['hips', 'ankles'], 'Sustained flat-footed deep-squat hold variant emphasizing ankle dorsiflexion specifically; a common assessment and training tool for ankle/hip mobility ceiling.', array['bodyweight'], 1, '3 min hold', false, true, 'https://www.youtube.com/watch?v=4Vk1Xq5IBLY', false),
  ('Single-Leg Balance (eyes closed)', 'balance', 'balance', array['total_body_resilience'], array['ankles'], 'Proprioceptive ankle/balance work; tracks single-leg stability improvement directly relevant to lateral-movement injury risk.', array['bodyweight'], 3, '30-45s hold', true, true, 'https://www.youtube.com/watch?v=4te4hHs2_Cc', false),
  ('Single-Leg Balance on Pillow', 'balance', 'balance', array['total_body_resilience'], array['ankles', 'feet'], 'Unstable-surface balance progression beyond the eyes-closed floor variant; builds ankle proprioception under perturbation.', array['balance_pad'], 3, '30-45s hold', true, true, null, false),
  ('Bosu Ball Squat', 'squat', 'balance', array['total_body_resilience'], array['hips', 'ankles', 'knees'], 'Combines squat-pattern strength with unstable-surface balance demand; bridges strength and stability training.', array['bosu_ball'], 3, '8-10', false, false, null, false),
  ('Single-Leg Romanian Deadlift Balance Reach', 'balance', 'balance', array['total_body_resilience'], array['ankles', 'hips', 'hamstrings'], 'Unilateral balance-under-load challenge that doubles as posterior-chain activation; strong carryover to pickleball''s single-leg landings.', array['dumbbell'], 3, '8-10', true, false, 'https://www.youtube.com/watch?v=tJtjeKtZWtY', false),
  ('Weighted Ankle Dorsiflexion Mobilization', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['ankles'], 'Loaded knee-to-wall mobilization using a light external load at the knee; progresses the unloaded wall ankle test once baseline dorsiflexion range improves.', array['light_plate'], 3, '10 reps/side', true, true, null, false),
  ('Half-Kneeling Ankle Mobilization', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['ankles'], 'Half-kneeling rock-forward drill loading dorsiflexion under bodyweight; a no-equipment complement to the banded ankle distraction for days without a band.', array['bodyweight'], 3, '8-10 reps/side', true, true, 'https://www.youtube.com/watch?v=PgC2gQ4inHE', false),
  ('Ankle Circles', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['ankles'], 'Simple active range-of-motion warmup; loosens the ankle joint capsule before loading.', array['bodyweight'], 2, '10 reps/side', true, true, null, false),
  ('Calf Raise Stretch on Step', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['ankles'], 'Static calf/Achilles stretch off a step edge; addresses posterior ankle tightness that limits dorsiflexion.', array['step'], 2, '30-45s hold', true, true, 'https://www.youtube.com/watch?v=zYZJ4Bm8E0E', false),
  ('Seated Ankle Dorsiflexion with Band', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['ankles'], 'Banded mobilization targeting dorsiflexion specifically; complements the standing banded distraction with a seated, lower-load variant.', array['resistance_band'], 3, '12-15 reps/side', true, true, null, false),
  ('Single-Leg Calf Raise', 'push', 'strength', array['total_body_resilience', 'aesthetic_physique'], array['ankles', 'feet'], 'Builds calf strength and ankle-stabilizer endurance unilaterally -- directly protective against the lateral-pickleball reinjury pattern CLAUDE.md flags.', array['bodyweight'], 3, '12-15', true, false, 'https://www.youtube.com/watch?v=gwLzBJYoWlI', false),
  ('Glute-Ham Raise', 'hinge', 'strength', array['total_body_resilience'], array['hamstrings'], 'Machine-assisted hamstring-curl movement sharing the Nordic curl''s eccentric-loading evidence base; a regression option when bodyweight Nordic curls are too advanced.', array['glute_ham_developer'], 3, '6-10', false, true, 'https://www.youtube.com/watch?v=raN1aShnf3I', true),
  ('Active Straight-Leg Raise Hamstring Stretch', 'hinge', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['hamstrings'], 'Supine active-assisted hamstring stretch using a strap; complements the PNF contract-relax method with an active end-range hold.', array['strap'], 1, '3 reps/side hold 15s', true, true, 'https://www.youtube.com/watch?v=8a6yMaSrFOc', false),
  ('Deep Lunge Hip Opener', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['hips'], 'Kneeling deep-lunge hip-opener stretch; complements the 90/90''s rotational hip work with an extension-biased anterior-hip target.', array['yoga_mat'], 1, '60s hold/side', true, true, null, false),
  ('Half-Kneeling Hip Flexor Stretch with Reach', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['hips'], 'Active variant of the couch stretch adding an overhead reach to bias the rectus femoris and add a thoracic-extension component.', array['bodyweight'], 1, '45-60s hold/side', true, true, 'https://www.youtube.com/watch?v=g_tea8ZNk5A', false),
  ('Standing Hamstring Stretch', 'hinge', 'mobility_stretch', array['mobility_flexibility'], array['hamstrings'], 'Simple static hamstring stretch; low-skill complement to the PNF variant on lower-readiness days.', array['bodyweight'], 1, '30-60s hold/side', true, true, null, false),
  ('Pigeon Pose', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['hips'], 'Deep hip external-rotator stretch; common yoga pose with strong carryover to hip-opening goals CLAUDE.md emphasizes.', array['yoga_mat'], 1, '60-90s hold/side', true, true, 'https://www.youtube.com/watch?v=cUyJaHO9Vp4', false),
  ('Frog Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['hips'], 'Adductor/hip-opener stretch complementing the 90/90 and couch stretch from a different angle of hip mobility.', array['yoga_mat'], 1, '60-90s hold', false, true, null, false),
  ('World''s Greatest Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['hips', 'thoracic_spine', 'hamstrings'], 'Combination lunge-rotation-hamstring stretch; efficient multi-joint mobility movement for a pre-lift warmup or recovery day.', array['bodyweight'], 2, '5 reps/side', true, false, 'https://www.youtube.com/watch?v=hUH2tT2-T-c', false),
  ('Side-Lying Hip Adduction', 'core', 'strength', array['total_body_resilience'], array['hips', 'hamstrings'], 'Side-lying adductor-strengthening movement; a lower-skill regression toward the full Copenhagen plank for building the same adductor/groin strength.', array['bodyweight'], 3, '12-15/side', true, true, null, false),
  ('Adductor Stretch (seated)', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['hips'], 'Static adductor/groin stretch; complements the Copenhagen plank''s strength work with passive range-of-motion.', array['yoga_mat'], 1, '45-60s hold', false, true, null, false),
  ('Romanian Deadlift', 'hinge', 'strength', array['strength_power', 'aesthetic_physique'], array['hamstrings', 'lower_back'], 'Hip-hinge hypertrophy/strength staple targeting the posterior chain through a long hamstring range of motion.', array['barbell'], 3, '8-10', false, false, 'https://www.youtube.com/watch?v=jEy_czb3RKA', true),
  ('Dumbbell Romanian Deadlift', 'hinge', 'strength', array['aesthetic_physique', 'total_body_resilience'], array['hamstrings', 'lower_back'], 'Lower-load equipment variant of the barbell RDL; more accessible bar path for hip-hinge skill development.', array['dumbbell'], 3, '10-12', false, false, 'https://www.youtube.com/watch?v=1uDiW5--rAE', false),
  ('Conventional Deadlift', 'hinge', 'strength', array['strength_power'], array['hamstrings', 'lower_back'], 'Full-body hip-hinge strength staple; among the highest-loading compound exercises for total posterior-chain development.', array['barbell'], 3, '3-5', false, false, 'https://www.youtube.com/watch?v=op9kVnSso6Q', true),
  ('Trap Bar Deadlift', 'hinge', 'strength', array['strength_power', 'total_body_resilience'], array['hamstrings', 'lower_back'], 'More upright torso position than a conventional deadlift, reducing lower-back shear while keeping the hip-hinge loading benefit.', array['trap_bar'], 3, '5-8', false, false, 'https://www.youtube.com/watch?v=qIYWAVJ4lq4', true),
  ('Single-Leg Romanian Deadlift', 'hinge', 'strength', array['total_body_resilience', 'strength_power'], array['hamstrings', 'ankles'], 'Unilateral hip-hinge that trains hamstring strength and balance together; closes left/right asymmetry per CLAUDE.md''s unilateral-from-the-left principle.', array['dumbbell'], 3, '8-10', true, false, 'https://www.youtube.com/watch?v=2yjwXTZQDDI', true),
  ('Cable Pull-Through', 'hinge', 'strength', array['aesthetic_physique', 'total_body_resilience'], array['hamstrings', 'hips'], 'Reinforces hip-hinge mechanics under constant cable tension; lower skill demand than a barbell hinge for the same posterior-chain target.', array['cable_machine'], 3, '12-15', false, false, 'https://www.youtube.com/watch?v=h9rTP2gMsTo', false),
  ('Glute Bridge', 'hinge', 'strength', array['total_body_resilience', 'aesthetic_physique'], array['hips', 'lower_back'], 'Foundational glute-activation hinge pattern; useful as both a warmup primer and a standalone hypertrophy movement.', array['bodyweight'], 3, '12-15', false, false, 'https://www.youtube.com/watch?v=wPM8icPu6H8', false),
  ('Hip Thrust', 'hinge', 'strength', array['aesthetic_physique', 'strength_power'], array['hips'], 'Loaded glute-focused hinge variant with strong evidence for glute hypertrophy specifically versus squats/deadlifts alone.', array['barbell', 'bench'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=xDZgZWvJ-1U', false),
  ('Good Morning', 'hinge', 'strength', array['strength_power', 'total_body_resilience'], array['hamstrings', 'lower_back'], 'Hip-hinge accessory that isolates posterior-chain strength under bar load without the grip/setup demand of a deadlift.', array['barbell'], 3, '8-10', false, false, 'https://www.youtube.com/watch?v=PrJoMfee62I', true),
  ('Kettlebell Swing', 'hinge', 'plyometric', array['total_body_resilience', 'endurance'], array['hamstrings', 'hips'], 'Ballistic hip-hinge that builds explosive posterior-chain power and conditioning simultaneously.', array['kettlebell'], 3, '15-20', false, false, 'https://www.youtube.com/watch?v=YSx7N1Sk7Yc', true),
  ('Standing Toe Touch with Reach-Through', 'hinge', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['lower_back', 'hamstrings'], 'Standing segmental spinal-flexion stretch reaching toward the floor; a bodyweight-only complement to the loaded Jefferson curl for days without a barbell.', array['bodyweight'], 2, '8-10', false, true, null, false),
  ('Bird Dog', 'core', 'strength', array['total_body_resilience'], array['lower_back', 'hips'], 'Anti-rotation core-stability movement with strong evidence for safe lower-back loading and motor control.', array['bodyweight'], 3, '8-10/side', true, false, 'https://www.youtube.com/watch?v=wiFNA3sqjCA', false),
  ('Plank', 'core', 'strength', array['total_body_resilience'], array['lower_back'], 'Foundational anti-extension core hold; baseline core-endurance movement with minimal equipment demand.', array['bodyweight'], 3, '30-60s hold', false, false, 'https://www.youtube.com/watch?v=pSHjTRCQxIw', false),
  ('Side Plank', 'core', 'strength', array['total_body_resilience'], array['lower_back', 'hips'], 'Anti-lateral-flexion core hold; trains the obliques and quadratus lumborum in a way a front plank does not.', array['bodyweight'], 3, '30-45s hold/side', true, false, 'https://www.youtube.com/watch?v=K2VljzCC16g', false),
  ('Hanging Leg Raise', 'core', 'strength', array['aesthetic_physique', 'strength_power'], array['lower_back'], 'Loaded anti-extension/flexion core movement with strong hypertrophy carryover to visible lower-ab definition.', array['pull_up_bar'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=Pr1ieGZ5atk', true),
  ('Cable Woodchop', 'core', 'strength', array['aesthetic_physique', 'total_body_resilience'], array['lower_back', 'hips'], 'Rotational core-strength movement; trains the anti-rotation/rotation pattern pickleball''s swing mechanics demand.', array['cable_machine'], 3, '10-12/side', true, false, 'https://www.youtube.com/watch?v=2VOOgz6mApk', false),
  ('Dead Bug', 'core', 'strength', array['total_body_resilience'], array['lower_back'], 'Low-load anti-extension core movement with excellent motor-control carryover; common physical-therapy staple for lower-back resilience.', array['bodyweight'], 3, '8-10/side', true, true, 'https://www.youtube.com/watch?v=8GcGvKqz5Sw', false),
  ('Ab Wheel Rollout', 'core', 'strength', array['aesthetic_physique', 'strength_power'], array['lower_back'], 'Advanced anti-extension core movement under long lever arm; high core-strength carryover once plank/dead-bug progressions are mastered.', array['ab_wheel'], 3, '6-10', false, false, 'https://www.youtube.com/watch?v=09c5T-vSyJk', true),
  ('Hollow Body Hold', 'core', 'strength', array['aesthetic_physique', 'total_body_resilience'], array['lower_back'], 'Gymnastics-derived core-bracing hold; builds the full-body tension skill that transfers to bracing under a barbell.', array['bodyweight'], 3, '20-30s hold', false, false, 'https://www.youtube.com/watch?v=Ml0Plg8E_4Y', false),
  ('Cat-Cow', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['thoracic_spine', 'lower_back'], 'Dynamic spinal-segment mobility flow; gentle warmup movement for the whole spine before loaded work.', array['bodyweight'], 2, '8-10 reps', false, true, 'https://www.youtube.com/watch?v=kqnua4rHVVA', false),
  ('Wall-Supported Chin Tuck', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['neck'], 'Wall-supported variant of the chin tuck adding tactile feedback for correct cervical retraction depth; useful cueing progression for forward-head posture correction.', array['wall'], 3, '10 reps', false, true, 'https://www.youtube.com/watch?v=cVtq1xeQfTI', false),
  ('Thoracic Rotation on Foam Roller', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['thoracic_spine'], 'Foam-roller-supported thoracic rotation drill; complements the extension-only foam-roller variant with a rotational axis of thoracic mobility.', array['foam_roller'], 2, '8-10 reps/side', true, true, 'https://www.youtube.com/watch?v=1Hp9bLZ4hSU', false),
  ('Scalene Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['neck'], 'Targets the scalene muscle group from a different angle than the levator scapulae stretch; both commonly co-tight contributors to chronic neck stiffness.', array['bodyweight'], 1, '30s hold/side', true, true, null, false),
  ('Neck Rotation Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['neck'], 'Active rotational neck range-of-motion movement; complements the levator scapulae and chin-tuck work from a different plane of motion.', array['bodyweight'], 2, '8-10 reps/side', true, true, null, false),
  ('Upper Trap Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['neck'], 'Lateral-flexion stretch targeting the upper trapezius, a common source of referred neck tension alongside the levator scapulae.', array['bodyweight'], 1, '30-45s hold/side', true, true, 'https://www.youtube.com/watch?v=KSlSWXrxAQU', false),
  ('Scapular Wall Slides', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['shoulders', 'thoracic_spine'], 'Reinforces scapular upward rotation and thoracic extension together; corrective groundwork before overhead pressing.', array['wall'], 2, '10-12 reps', false, true, 'https://www.youtube.com/watch?v=BgcN-eetGmM', false),
  ('Thread the Needle', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['thoracic_spine'], 'Rotational thoracic-spine mobility movement performed on all fours; complements the foam-roller extension with a rotational axis.', array['bodyweight'], 2, '8-10 reps/side', true, false, 'https://www.youtube.com/watch?v=1DPceVbWX-w', false),
  ('Standing Forward Fold with Shoulder Flexion', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['shoulders', 'hamstrings'], 'Standing variant combining a hamstring stretch with overhead shoulder flexion; a no-mat alternative to the down dog progression with a similar combined-mobility target.', array['bodyweight'], 1, '30-45s hold', false, true, null, false),
  ('Cross-Arm Internal Rotation Stretch (right)', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['shoulders'], 'Standing internal-rotation stretch targeting the same posterior shoulder-capsule tightness as the sleeper stretch from a standing position rather than side-lying.', array['bodyweight'], 1, '30s hold', true, true, 'https://www.youtube.com/watch?v=NJ0fGiyc7dM', false),
  ('Wall Slide with External Rotation', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['shoulders'], 'Combines the scapular wall slide with an external-rotation finish; corrective groundwork for shoulder-capsule health distinct from the v1 Shoulder CARs entry.', array['wall'], 2, '8-10 reps', false, true, 'https://www.youtube.com/watch?v=BgcN-eetGmM', false),
  ('Cross-Body Shoulder Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['shoulders'], 'Simple posterior-deltoid stretch; lower-skill complement to the sleeper stretch for general shoulder tightness.', array['bodyweight'], 1, '30s hold/side', true, true, null, false),
  ('Doorway Pec Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['shoulders'], 'Anterior-chain shoulder/chest stretch; counters the internally-rotated posture that exacerbates right-shoulder tightness.', array['doorway'], 1, '30-45s hold/side', true, true, 'https://www.youtube.com/watch?v=AyJSWZHb1Z8', false),
  ('Band Pull-Apart', 'pull', 'strength', array['total_body_resilience', 'aesthetic_physique'], array['shoulders'], 'Light high-rep posterior-shoulder/upper-back activation movement; common prehab staple for shoulder-health and posture.', array['resistance_band'], 3, '15-20', false, true, 'https://www.youtube.com/watch?v=9c4ZZUDmfgg', false),
  ('Face Pull', 'pull', 'strength', array['total_body_resilience', 'aesthetic_physique'], array['shoulders'], 'Targets the rear delts and external rotators directly; widely used corrective accessory for shoulder-health and posture balance.', array['cable_machine'], 3, '12-15', false, true, 'https://www.youtube.com/watch?v=rep-qVOkqgk', false),
  ('Barbell Bench Press', 'push', 'strength', array['strength_power', 'aesthetic_physique'], array['shoulders'], 'Foundational horizontal-press compound; among the most evidence-backed movements for chest/shoulder/triceps strength and size.', array['barbell', 'bench'], 4, '5-8', false, false, 'https://www.youtube.com/watch?v=rT7DgCr-3pg', true),
  ('Dumbbell Bench Press', 'push', 'strength', array['aesthetic_physique', 'strength_power'], array['shoulders'], 'Greater range of motion and unilateral stabilizer demand than the barbell variant, with lower injury risk from a fixed bar path.', array['dumbbell', 'bench'], 3, '8-10', false, false, 'https://www.youtube.com/watch?v=VmB1G1K7v94', false),
  ('Incline Barbell Press', 'push', 'strength', array['aesthetic_physique', 'strength_power'], array['shoulders'], 'Upper-chest-emphasis press variant; fills out the shoulder girdle in a way flat pressing alone does not.', array['barbell', 'bench'], 3, '6-10', false, false, 'https://www.youtube.com/watch?v=SrqOu55lrYU', true),
  ('Incline Dumbbell Press', 'push', 'strength', array['aesthetic_physique'], array['shoulders'], 'Equipment variant of the incline press with a longer range of motion and independent-arm stabilizer demand.', array['dumbbell', 'bench'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=8iPEnn-ltC8', false),
  ('Incline Smith Machine Press', 'push', 'strength', array['aesthetic_physique'], array['shoulders'], 'Fixed-path incline press variant; lets a lifter push closer to failure safely without a spotter.', array['smith_machine', 'bench'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=Sb9Yx7q7c7w', false),
  ('Overhead Press', 'push', 'strength', array['strength_power', 'aesthetic_physique'], array['shoulders'], 'Vertical-press compound building shoulder strength and stability through full overhead range -- directly relevant to filling out the shoulder girdle.', array['barbell'], 3, '5-8', false, false, 'https://www.youtube.com/watch?v=2yjwXTZQDDI', true),
  ('Dumbbell Shoulder Press', 'push', 'strength', array['aesthetic_physique'], array['shoulders'], 'Dumbbell variant of the overhead press; independent-arm path helps correct left/right shoulder imbalance.', array['dumbbell'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=qEwKCR5JCog', false),
  ('Push-Up', 'push', 'strength', array['total_body_resilience', 'aesthetic_physique'], array['shoulders'], 'Bodyweight horizontal-press staple; scalable, equipment-free option for chest/shoulder/triceps strength.', array['bodyweight'], 3, '10-20', false, false, 'https://www.youtube.com/watch?v=IODxDxX7oi4', false),
  ('Dip', 'push', 'strength', array['aesthetic_physique', 'strength_power'], array['shoulders'], 'Bodyweight vertical-press movement emphasizing triceps and lower chest under a deep stretch range.', array['parallel_bars'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=2z8JmcrW-As', true),
  ('Cable Chest Fly', 'push', 'strength', array['aesthetic_physique'], array['shoulders'], 'Isolation movement for chest under constant cable tension; complements pressing with a stretch-focused hypertrophy stimulus.', array['cable_machine'], 3, '12-15', false, false, 'https://www.youtube.com/watch?v=Iwe6AmxVf7o', false),
  ('Landmine Press', 'push', 'strength', array['total_body_resilience', 'aesthetic_physique'], array['shoulders'], 'Shoulder-friendly pressing angle that reduces impingement risk while still building pressing strength; good option on a tender-shoulder day.', array['barbell', 'landmine_attachment'], 3, '8-12', true, false, 'https://www.youtube.com/watch?v=GcWX_aB6PYI', false),
  ('Plyo Push-Up', 'push', 'plyometric', array['strength_power', 'aesthetic_physique'], array['shoulders'], 'Explosive upper-body pressing power movement; builds rate of force development for sports requiring fast hand/arm action.', array['bodyweight'], 3, '5-8', false, false, 'https://www.youtube.com/watch?v=NIvT2dM8DKs', true),
  ('Medicine Ball Chest Pass', 'push', 'plyometric', array['strength_power', 'endurance'], array['shoulders'], 'Explosive horizontal-press power movement transferable to pickleball''s quick reactive shots.', array['medicine_ball'], 3, '6-8', false, false, 'https://www.youtube.com/watch?v=jhTUWAIpDTw', false),
  ('Barbell Row', 'pull', 'strength', array['strength_power', 'aesthetic_physique'], array['shoulders', 'lower_back'], 'Foundational horizontal-pull compound; builds upper-back thickness directly addressing CLAUDE.md''s "fill out shoulders/upper back" goal.', array['barbell'], 3, '8-10', false, false, 'https://www.youtube.com/watch?v=9efgcAjQe7E', true),
  ('Dumbbell Row', 'pull', 'strength', array['aesthetic_physique', 'total_body_resilience'], array['shoulders', 'lower_back'], 'Unilateral horizontal-pull variant; trains each side of the upper back independently, supporting left/right correction.', array['dumbbell', 'bench'], 3, '8-12', true, false, 'https://www.youtube.com/watch?v=pYcpY20QaE8', false),
  ('Cable Row', 'pull', 'strength', array['aesthetic_physique'], array['shoulders'], 'Constant-tension horizontal-pull movement; easier on the lower back than a bent-over barbell row for high-volume back work.', array['cable_machine'], 3, '10-12', false, false, 'https://www.youtube.com/watch?v=GZbfZ033f74', false),
  ('Pull-Up', 'pull', 'strength', array['strength_power', 'aesthetic_physique'], array['shoulders'], 'Vertical-pull bodyweight staple with strong evidence for lat/upper-back strength and width.', array['pull_up_bar'], 3, '5-10', false, false, 'https://www.youtube.com/watch?v=eGo4IYlbE5g', true),
  ('Chin-Up', 'pull', 'strength', array['aesthetic_physique', 'strength_power'], array['shoulders'], 'Supinated-grip pull-up variant with greater biceps involvement; useful pulling-strength progression alongside the pull-up.', array['pull_up_bar'], 3, '5-10', false, false, 'https://www.youtube.com/watch?v=brhRXlOhsAM', false),
  ('Lat Pulldown', 'pull', 'strength', array['aesthetic_physique'], array['shoulders'], 'Machine vertical-pull movement; accessible regression toward a full pull-up while still building lat width.', array['cable_machine'], 3, '10-12', false, false, 'https://www.youtube.com/watch?v=CAwf7n6Luuc', false),
  ('Single-Arm Lat Pulldown', 'pull', 'strength', array['aesthetic_physique', 'total_body_resilience'], array['shoulders'], 'Unilateral vertical-pull variant; trains each lat independently, directly supporting CLAUDE.md''s left-first unilateral-correction principle.', array['cable_machine'], 3, '10-12', true, false, 'https://www.youtube.com/watch?v=hUBjp-z3HFA', false),
  ('Face-Down Reverse Fly', 'pull', 'strength', array['aesthetic_physique', 'total_body_resilience'], array['shoulders'], 'Rear-delt isolation movement on a bench; reinforces the posterior shoulder strength the face pull also targets.', array['dumbbell', 'bench'], 3, '12-15', false, false, 'https://www.youtube.com/watch?v=EA7u4Q_8HQ0', false),
  ('Seated Cable Row', 'pull', 'strength', array['aesthetic_physique'], array['shoulders', 'lower_back'], 'Seated horizontal-pull variant with strict torso bracing; good high-volume upper-back accessory.', array['cable_machine'], 3, '10-12', false, false, 'https://www.youtube.com/watch?v=GZbfZ033f74', false),
  ('Inverted Row', 'pull', 'strength', array['total_body_resilience', 'aesthetic_physique'], array['shoulders'], 'Bodyweight horizontal-pull regression using a bar or rings; useful entry point toward weighted rowing strength.', array['barbell', 'squat_rack'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=KOyMlSqJPyU', false),
  ('Barbell Curl', 'pull', 'strength', array['aesthetic_physique'], array['elbows'], 'Classic biceps isolation movement; supports visible arm definition alongside the program''s compound-first emphasis.', array['barbell'], 3, '8-12', false, false, 'https://www.youtube.com/watch?v=kwG2ipFRgfo', false),
  ('Dumbbell Curl', 'pull', 'strength', array['aesthetic_physique'], array['elbows'], 'Unilateral biceps isolation; independent-arm path supports correcting right-arm dominance.', array['dumbbell'], 3, '10-12', true, false, 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo', false),
  ('Hammer Curl', 'pull', 'strength', array['aesthetic_physique'], array['elbows', 'wrists'], 'Neutral-grip biceps/forearm variant; adds forearm and brachialis development alongside standard curls.', array['dumbbell'], 3, '10-12', true, false, 'https://www.youtube.com/watch?v=zC3nLlEvin4', false),
  ('Tricep Pushdown', 'push', 'strength', array['aesthetic_physique'], array['elbows'], 'Isolation movement for triceps under constant cable tension; complements compound pressing for arm definition.', array['cable_machine'], 3, '10-15', false, false, 'https://www.youtube.com/watch?v=2-LAMcpzODU', false),
  ('Overhead Tricep Extension', 'push', 'strength', array['aesthetic_physique'], array['elbows'], 'Stretch-focused triceps isolation movement; targets the long head more than pushdown variants.', array['dumbbell'], 3, '10-12', false, false, 'https://www.youtube.com/watch?v=YbX7Wd8jQ-Q', false),
  ('Wrist Curl', 'push', 'strength', array['total_body_resilience'], array['wrists'], 'Direct forearm-flexor strengthening; protective for wrist-loaded lifts like front squats and overhead pressing.', array['dumbbell'], 3, '12-15', false, true, 'https://www.youtube.com/watch?v=PEgcVChksjE', false),
  ('Reverse Wrist Curl', 'pull', 'strength', array['total_body_resilience'], array['wrists'], 'Forearm-extensor strengthening that balances the wrist curl''s flexor work; protective against wrist overuse.', array['dumbbell'], 3, '12-15', false, true, null, false),
  ('Wrist Mobility Flow (flexion/extension/circles)', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['wrists'], 'Combined active-mobility flow for the wrist joint; useful pre-lift prep before any bar-loaded pressing or front-rack work.', array['bodyweight'], 2, '10 reps each direction', true, true, null, false),
  ('Farmer''s Carry', 'pull', 'strength', array['total_body_resilience', 'strength_power'], array['wrists', 'lower_back'], 'Loaded carry building grip, forearm, and trunk stability simultaneously; high carryover to real-world load-bearing tasks.', array['dumbbell_or_kettlebell'], 3, '30-40m', false, false, 'https://www.youtube.com/watch?v=Fkzk_RqlYig', false),
  ('Suitcase Carry', 'pull', 'strength', array['total_body_resilience'], array['lower_back', 'wrists'], 'Unilateral loaded carry that challenges anti-lateral-flexion core stability alongside grip strength.', array['dumbbell_or_kettlebell'], 3, '30-40m/side', true, false, 'https://www.youtube.com/watch?v=u8AHcwGiD-U', false),
  ('Lateral Lunge', 'squat', 'strength', array['total_body_resilience'], array['hips', 'knees', 'ankles'], 'Frontal-plane lunge variant; directly trains the lateral movement pattern pickleball demands, beyond sagittal-plane squats/lunges.', array['dumbbell'], 3, '8-10/side', true, false, 'https://www.youtube.com/watch?v=3MAuCpFTGTI', false),
  ('Lateral Band Walk', 'squat', 'strength', array['total_body_resilience'], array['hips', 'knees'], 'Glute-medius activation movement under lateral resistance; a common pickleball/lateral-sport injury-prevention staple.', array['resistance_band'], 3, '10-15 steps/side', true, true, 'https://www.youtube.com/watch?v=wYzwk4dW-Yc', false),
  ('Monster Walk', 'squat', 'strength', array['total_body_resilience'], array['hips', 'ankles'], 'Multi-directional banded walking drill that builds hip-abductor and ankle-stabilizer endurance together.', array['resistance_band'], 3, '10 steps each direction', true, true, null, false),
  ('Lateral Hop', 'squat', 'plyometric', array['total_body_resilience', 'strength_power'], array['ankles', 'knees'], 'Single-plane plyometric hop building lateral-landing control directly relevant to pickleball''s side-to-side footwork and ankle reinjury risk.', array['bodyweight'], 3, '6-8/side', true, false, 'https://www.youtube.com/watch?v=Rm1Ee7XaUSY', false),
  ('Skater Hop', 'squat', 'plyometric', array['total_body_resilience', 'strength_power'], array['ankles', 'hips'], 'Lateral bounding plyometric that mirrors pickleball''s lateral cutting demand while training single-leg landing absorption.', array['bodyweight'], 3, '6-8/side', true, false, 'https://www.youtube.com/watch?v=O4XLeF6V_lE', false),
  ('Depth Jump', 'squat', 'plyometric', array['strength_power'], array['knees', 'ankles'], 'Reactive-strength plyometric using a drop into an immediate jump; builds fast eccentric-to-concentric force transfer.', array['plyo_box'], 3, '4-5', false, false, 'https://www.youtube.com/watch?v=eOO5jK5ouhY', true),
  ('Broad Jump', 'squat', 'plyometric', array['strength_power', 'total_body_resilience'], array['hips', 'knees'], 'Horizontal explosive triple-extension movement; complements the vertical box jump with a different force vector.', array['bodyweight'], 3, '3-5', false, false, 'https://www.youtube.com/watch?v=k09GFRZuQ_g', false),
  ('Tuck Jump', 'squat', 'plyometric', array['strength_power'], array['hips', 'knees'], 'High-intensity plyometric demanding rapid hip flexion under flight time; advanced progression once landing mechanics are solid.', array['bodyweight'], 3, '5-6', false, false, 'https://www.youtube.com/watch?v=hxa-03kuBuc', false),
  ('Med Ball Slam', 'core', 'plyometric', array['strength_power', 'endurance'], array['lower_back'], 'Explosive total-body power movement through the core and shoulders; doubles as a high-intensity conditioning finisher.', array['medicine_ball'], 3, '8-10', false, false, 'https://www.youtube.com/watch?v=qzhP1VR-VLE', false),
  ('Med Ball Rotational Throw', 'core', 'plyometric', array['strength_power', 'total_body_resilience'], array['lower_back', 'hips'], 'Explosive rotational power movement mirroring the trunk-rotation demand of a pickleball groundstroke.', array['medicine_ball'], 3, '6-8/side', true, false, 'https://www.youtube.com/watch?v=BNxXz9deZbA', false),
  ('Plyo Lunge (alternating jump lunge)', 'squat', 'plyometric', array['strength_power', 'total_body_resilience'], array['hips', 'knees'], 'Explosive alternating-leg lunge; builds single-leg power and reactive landing control together.', array['bodyweight'], 3, '6-8/side', true, false, 'https://www.youtube.com/watch?v=ZVfXrWyowYs', false),
  ('Pickleball-Specific Lateral Shuffle', 'squat', 'cardio', array['endurance', 'total_body_resilience'], array['ankles', 'hips'], 'Sport-specific lateral conditioning drill mirroring pickleball court movement; doubles as dynamic ankle/hip warmup before play.', array['cones_or_floor_markers'], 3, '20-30s', false, false, null, false),
  ('Jump Rope', 'squat', 'cardio', array['endurance', 'total_body_resilience'], array['ankles'], 'Low-equipment cardio/conditioning movement that also reinforces ankle stiffness and rhythm under repeated ground contact.', array['jump_rope'], 3, '60-90s', false, false, 'https://www.youtube.com/watch?v=u3zgHI8QnqE', false),
  ('Treadmill Incline Walk', 'squat', 'cardio', array['endurance', 'longevity_recovery'], array['ankles', 'hips'], 'Low-impact steady-state cardio option; useful active-recovery alternative to a full run on a lower-readiness day.', array['treadmill'], 1, '20-30 min', false, false, null, false),
  ('Easy Aerobic Run', 'squat', 'cardio', array['endurance', 'longevity_recovery'], array['ankles', 'knees'], 'Base-building steady-state run; the foundation CLAUDE.md''s 10%/week progression cap is built around.', array['none'], 1, '20-30 min', false, false, null, false),
  ('Interval Sprints', 'squat', 'cardio', array['endurance', 'strength_power'], array['ankles', 'hamstrings'], 'Higher-intensity running variant for VO2/speed development once aerobic base and hamstring resilience (Nordic curls) are established.', array['none'], 1, '6-8x30s', false, false, null, false),
  ('Stationary Bike', 'squat', 'cardio', array['endurance', 'longevity_recovery'], array['knees'], 'Low-impact cardio alternative that maintains aerobic conditioning while fully offloading the ankles -- useful during an ankle flare-up.', array['stationary_bike'], 1, '20-30 min', false, true, null, false),
  ('Rowing Machine', 'pull', 'cardio', array['endurance', 'strength_power'], array['lower_back', 'shoulders'], 'Full-body, low-impact cardio modality that also reinforces hip-hinge and pulling-pattern endurance.', array['rowing_machine'], 1, '15-20 min', false, false, 'https://www.youtube.com/watch?v=H1OWfPKWIIg', false),
  ('Battle Ropes', 'pull', 'cardio', array['endurance', 'strength_power'], array['shoulders'], 'High-intensity upper-body conditioning movement; builds shoulder/grip endurance under a metabolic-conditioning stimulus.', array['battle_ropes'], 3, '20-30s', false, false, 'https://www.youtube.com/watch?v=r0_KaSiCOWk', false),
  ('Sled Push', 'squat', 'cardio', array['strength_power', 'endurance'], array['hips', 'knees'], 'Concentric-only loaded conditioning movement; builds leg drive and aerobic capacity with minimal eccentric/soreness cost.', array['sled'], 3, '20-30m', false, false, 'https://www.youtube.com/watch?v=2VOOgz6mApk', false),
  ('Sled Drag (reverse)', 'squat', 'cardio', array['total_body_resilience', 'endurance'], array['knees', 'ankles'], 'Reverse sled drag is a common knee/ankle-friendly conditioning and rehab movement with very low joint shear.', array['sled'], 3, '20-30m', false, true, null, false),
  ('Farmer''s Carry Conditioning Circuit', 'pull', 'cardio', array['endurance', 'strength_power'], array['wrists', 'lower_back'], 'Combines loaded-carry strength with a conditioning stimulus when performed for extended distance/time.', array['dumbbell_or_kettlebell'], 3, '60-90s', false, false, null, false),
  ('Mountain Climbers', 'core', 'cardio', array['endurance', 'aesthetic_physique'], array['lower_back'], 'Dynamic core-and-conditioning movement combining a plank hold with continuous hip flexion under tempo.', array['bodyweight'], 3, '30-40s', false, false, 'https://www.youtube.com/watch?v=nmwgirgXLYM', false),
  ('Burpee', 'push', 'cardio', array['endurance', 'strength_power'], array['shoulders', 'ankles'], 'High-intensity total-body conditioning movement combining a push-up, squat, and jump in one sequence.', array['bodyweight'], 3, '8-10', false, false, 'https://www.youtube.com/watch?v=auBLPXO8Fww', false),
  ('Kettlebell Swing Conditioning Set', 'hinge', 'cardio', array['endurance', 'strength_power'], array['hamstrings', 'hips'], 'Extended-set kettlebell swing work shifts the same hip-hinge pattern from strength/power toward a conditioning stimulus.', array['kettlebell'], 3, '45-60s', false, false, 'https://www.youtube.com/watch?v=YSx7N1Sk7Yc', true),
  ('Standing Quad Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['knees'], 'Simple static quad/knee-extensor stretch; useful complement to the couch stretch for anterior thigh tightness.', array['bodyweight'], 1, '30-45s hold/side', true, false, null, false),
  ('Foam Roll Quads', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'longevity_recovery'], array['knees'], 'Self-myofascial release for the quads; common pre/post-session recovery tool to reduce stiffness.', array['foam_roller'], 1, '60-90s/side', true, false, null, false),
  ('Foam Roll IT Band', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'longevity_recovery'], array['hips', 'knees'], 'Self-myofascial release targeting the IT band, a common source of lateral knee/hip tightness in runners and lateral-sport athletes.', array['foam_roller'], 1, '60-90s/side', true, true, null, false),
  ('Calf Foam Roll', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'longevity_recovery'], array['ankles'], 'Self-myofascial release for the calves; complements the banded ankle distraction by addressing soft-tissue restriction.', array['foam_roller'], 1, '60-90s/side', true, true, null, false),
  ('Childs Pose', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'longevity_recovery'], array['lower_back', 'shoulders'], 'Restorative yoga pose lengthening the lats and lower back; common cool-down/recovery-day movement.', array['yoga_mat'], 1, '60-90s hold', false, false, 'https://www.youtube.com/watch?v=2MJGg-dUKh0', false),
  ('Knee-to-Chest Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['lower_back', 'hips'], 'Simple supine lower-back/hip stretch; gentle option on a high-soreness or low-readiness day.', array['bodyweight'], 1, '30-45s hold/side', true, false, null, false),
  ('Single-Leg Glute Bridge', 'hinge', 'strength', array['total_body_resilience'], array['hips', 'hamstrings'], 'Unilateral hinge variant isolating one side''s glute/hamstring strength; supports left-first correction work.', array['bodyweight'], 3, '10-12/side', true, false, 'https://www.youtube.com/watch?v=KE2WW1KMQjI', false),
  ('Clamshell', 'squat', 'strength', array['total_body_resilience'], array['hips'], 'Classic glute-medius activation/rehab movement; common corrective exercise for hip-stability deficits feeding into knee/ankle issues.', array['resistance_band'], 3, '12-15/side', true, true, 'https://www.youtube.com/watch?v=PvWeQAYS7CY', false),
  ('Fire Hydrant', 'squat', 'strength', array['total_body_resilience'], array['hips'], 'Hip-abductor activation movement on all fours; complements the clamshell and lateral band walk for glute-medius strength.', array['bodyweight'], 3, '10-12/side', true, true, 'https://www.youtube.com/watch?v=qVTGdYsLP9k', false),
  ('Standing Hip Flexor Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['hips'], 'Standing variant of the couch stretch''s anterior-hip target; useful when no bench/wall is available (e.g. between pickleball games).', array['bodyweight'], 1, '30-45s hold/side', true, true, null, false),
  ('90/90 Hip Switch', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['hips'], 'Dynamic transition variant of the static 90/90 stretch; builds active internal/external hip rotation control, not just passive range.', array['bodyweight'], 2, '6-8 transitions/side', true, false, 'https://www.youtube.com/watch?v=oN7BCK-zfgY', false),
  ('Reverse Nordic Curl', 'squat', 'strength', array['total_body_resilience'], array['knees'], 'Eccentric quad-strengthening movement using a kneeling lowering pattern; common knee-health corrective alongside the (hamstring) Nordic curl.', array['bodyweight'], 3, '5-8', false, true, 'https://www.youtube.com/watch?v=jK6w6PZNmHg', true),
  ('Terminal Knee Extension', 'squat', 'strength', array['total_body_resilience'], array['knees'], 'Banded knee-extension corrective targeting the VMO; widely used in knee-rehab programming for joint stability.', array['resistance_band'], 3, '12-15/side', true, true, 'https://www.youtube.com/watch?v=8WZpJ5jD4Wk', false),
  ('Seated Figure-4 Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['hips'], 'Seated piriformis/glute stretch; lower-skill alternative to the pigeon pose for hip external-rotator tightness.', array['bench'], 1, '30-45s hold/side', true, true, null, false),
  ('Banded Shoulder External Rotation', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['shoulders'], 'Rotator-cuff strengthening/corrective movement; protective against the impingement risk a tight right shoulder carries into pressing work.', array['resistance_band'], 3, '12-15/side', true, true, 'https://www.youtube.com/watch?v=2-LAMcpzODU', false),
  ('Y-T-W Raises', 'pull', 'strength', array['total_body_resilience', 'aesthetic_physique'], array['shoulders'], 'Light-load scapular-stabilizer activation sequence; common shoulder-health prehab movement done before or after pressing.', array['dumbbell'], 3, '8-10 each position', false, true, 'https://www.youtube.com/watch?v=NWAhA8wPVNU', false),
  ('Towel Behind-Back Shoulder Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['shoulders'], 'Internal/external rotation stretch using a towel; targets the same posterior-capsule tightness as the sleeper stretch from a different angle.', array['towel'], 1, '30s hold/side', true, true, null, false),
  ('Standing Calf Raise', 'push', 'strength', array['aesthetic_physique', 'total_body_resilience'], array['ankles'], 'Direct calf-strengthening movement; complements the single-leg calf raise with a bilateral, higher-load variant.', array['bodyweight_or_dumbbell'], 3, '12-15', false, false, 'https://www.youtube.com/watch?v=YMmgqO8Jo-k', false),
  ('Seated Calf Raise', 'push', 'strength', array['aesthetic_physique'], array['ankles'], 'Machine/seated calf variant emphasizing the soleus through a bent-knee position, complementing the standing gastrocnemius-biased raise.', array['calf_raise_machine'], 3, '12-15', false, false, 'https://www.youtube.com/watch?v=jpz5pV5VCKw', false),
  ('Eccentric Heel Drop', 'push', 'strength', array['total_body_resilience'], array['ankles'], 'Slow-eccentric calf-loading movement commonly used in Achilles-tendon rehab protocols; protective for ankle-adjacent tendon health.', array['step'], 3, '10-12', true, true, 'https://www.youtube.com/watch?v=AzVdF2nq8Hk', false),
  ('Toe Yoga', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['feet'], 'Intrinsic-foot-muscle control drill; builds the small stabilizer strength that underlies ankle stability higher up the chain.', array['bodyweight'], 2, '10 reps', true, true, null, false),
  ('Foot Doming (short foot exercise)', 'mobility', 'balance', array['total_body_resilience'], array['feet'], 'Arch-activation drill building intrinsic foot strength; common foundation movement in ankle-rehab and balance programming.', array['bodyweight'], 3, '10s hold x 8', true, true, null, false),
  ('Calf Raise on Step (eyes closed)', 'balance', 'balance', array['total_body_resilience'], array['ankles', 'feet'], 'Combines calf strengthening with a balance challenge by removing visual feedback; progression beyond the basic single-leg balance drill.', array['step'], 3, '8-10', true, true, null, false),
  ('Single-Leg Deadlift Reach to Cone', 'balance', 'balance', array['total_body_resilience'], array['ankles', 'hamstrings'], 'Functional balance drill combining hip-hinge mechanics with a reaching balance challenge; strong carryover to pickleball''s lunging reach.', array['cone_or_marker'], 3, '6-8/side', true, false, null, false),
  ('Bosu Ball Single-Leg Stand', 'balance', 'balance', array['total_body_resilience'], array['ankles'], 'Unstable-surface single-leg balance progression beyond a flat floor; builds ankle-stabilizer strength under perturbation.', array['bosu_ball'], 3, '30-45s/side', true, true, null, false),
  ('Tandem Stance Hold', 'balance', 'balance', array['total_body_resilience'], array['ankles', 'feet'], 'Heel-to-toe static balance hold; simple progression step between double-leg and single-leg balance work.', array['bodyweight'], 3, '30s hold', true, false, null, false),
  ('Y-Balance Reach', 'balance', 'balance', array['total_body_resilience'], array['ankles', 'hips'], 'Multi-directional single-leg reaching balance drill widely used as both an assessment and a training tool for lower-limb stability.', array['floor_markers'], 3, '3 reaches/side', true, false, 'https://www.youtube.com/watch?v=0nB6KqjJW0g', false),
  ('Agility Ladder Drill', 'squat', 'cardio', array['endurance', 'total_body_resilience'], array['ankles'], 'Fast-footwork conditioning drill that builds the rapid ankle-stabilization demand pickleball''s quick direction changes require.', array['agility_ladder'], 3, '20-30s', false, false, 'https://www.youtube.com/watch?v=qS3qfL0v5GE', false),
  ('Cone Shuttle Run', 'squat', 'cardio', array['endurance', 'strength_power'], array['ankles', 'knees'], 'Multi-directional sprint-and-cut conditioning drill mirroring real pickleball movement demand more closely than linear running alone.', array['cones'], 3, '20-30s', false, false, null, false),
  ('Resistance Band Shoulder Pass-Through', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['shoulders'], 'Dynamic overhead-mobility drill using a band; good pre-press warmup that doubles as a shoulder-health mobility movement.', array['resistance_band'], 2, '10-12 reps', false, false, 'https://www.youtube.com/watch?v=K0HZx2UejO0', false),
  ('Arm Circles', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['shoulders'], 'Simple dynamic shoulder warmup movement; low-skill entry point before loaded overhead or pressing work.', array['bodyweight'], 2, '10 reps each direction', false, false, null, false),
  ('Hip Circles', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['hips'], 'Dynamic hip-joint warmup movement; loosens the hip capsule through a full circular range before squatting or lunging.', array['bodyweight'], 2, '8-10 reps/side', true, false, null, false),
  ('Leg Swings', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['hips', 'hamstrings'], 'Dynamic swinging warmup for the hip and hamstring; common pre-run or pre-lift mobility primer.', array['bodyweight'], 2, '10-12 reps/side', true, false, null, false),
  ('Neck Isometric Holds (4-way)', 'mobility', 'strength', array['total_body_resilience', 'mobility_flexibility'], array['neck'], 'Light isometric resistance in flexion/extension/lateral directions builds deep cervical stabilizer endurance, addressing chronic neck stiffness at its strength root rather than only its mobility side.', array['bodyweight'], 2, '10s hold x 6 each direction', false, true, 'https://www.youtube.com/watch?v=cVtq1xeQfTI', false),
  ('Prone Neck Retraction with Extension', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'total_body_resilience'], array['neck', 'thoracic_spine'], 'Combines the chin-tuck retraction with thoracic extension lying face-down; reinforces the CLAUDE.md thoracic-spine-is-the-root-cause framing in one movement.', array['bodyweight'], 2, '8-10 reps', false, true, null, false),
  ('Suboccipital Release (massage ball)', 'mobility', 'mobility_stretch', array['mobility_flexibility', 'longevity_recovery'], array['neck'], 'Self-myofascial release at the skull base targeting the suboccipital muscles, a common contributor to chronic neck tension and tension headaches.', array['massage_ball'], 1, '60-90s', false, true, null, false),
  ('Cervical Lateral Flexion Stretch', 'mobility', 'mobility_stretch', array['mobility_flexibility'], array['neck'], 'Static side-bend neck stretch isolating the upper trap/scalene group from a different angle than the upper trap stretch''s shoulder-anchored variant.', array['bodyweight'], 1, '30s hold/side', true, true, null, false),
  ('Plank with Shoulder Taps', 'core', 'balance', array['total_body_resilience'], array['lower_back', 'shoulders'], 'Anti-rotation plank variant that adds an unstable-arm-lift balance challenge on top of the static core hold.', array['bodyweight'], 3, '8-10/side', true, false, 'https://www.youtube.com/watch?v=R5oWVbB6q9w', false),
  ('Cobra Stretch', 'core', 'mobility_stretch', array['mobility_flexibility'], array['lower_back'], 'Gentle prone spinal-extension stretch; common cool-down movement countering the spinal flexion of core/ab work.', array['bodyweight'], 1, '30-45s hold', false, false, 'https://www.youtube.com/watch?v=JDcdhTuycOI', false),
  ('Seated Wide-Leg Forward Fold', 'pull', 'mobility_stretch', array['mobility_flexibility'], array['hamstrings', 'hips'], 'Seated bilateral hamstring/adductor stretch performed in a position similar to a row''s seated base, complementing pulling-pattern training days.', array['yoga_mat'], 1, '45-60s hold', false, false, null, false),
  ('Renegade Row', 'pull', 'plyometric', array['strength_power', 'total_body_resilience'], array['shoulders', 'lower_back'], 'Unilateral rowing movement performed from a plank position under reactive core-stability demand; combines pulling strength with anti-rotation bracing power.', array['dumbbell'], 3, '6-8/side', true, false, 'https://www.youtube.com/watch?v=pAplQXk3dkA', false),
  ('Single-Arm Band Row to Balance Reach', 'pull', 'balance', array['total_body_resilience'], array['shoulders', 'ankles'], 'Combines a unilateral rowing pull with a single-leg balance hold, training upper-back pulling strength and ankle stability together.', array['resistance_band'], 3, '8-10/side', true, false, null, false),
  ('Push-Up to Single-Arm Reach', 'push', 'balance', array['total_body_resilience'], array['shoulders', 'wrists'], 'Adds a single-arm balance/reach component at the top of a push-up, training pressing strength alongside shoulder and wrist stability.', array['bodyweight'], 3, '5-6/side', true, false, null, false),
  ('Wrestler''s Bridge Hold', 'mobility', 'balance', array['total_body_resilience'], array['neck', 'thoracic_spine'], 'Supported neck/upper-back bridge hold building neck-extensor endurance and balance together; performed lightly and supported, not a high-load wrestling bridge.', array['yoga_mat'], 2, '15-20s hold', false, true, null, false);
